-- Insert statements for News data

INSERT INTO news (title, summary, content, source, category, image_url, url, published_at, created_at)
VALUES
    ('Stock futures are little changed as rate cut bets strengthen: Live updates - CNBC',
     'Investors took Wednesday''s ADP data as a signal that the Federal Reserve could be more inclined to cut interest rates at its upcoming Dec. 10 meeting.',
     'Stock futures are little changed on Thursday as investors grew more optimistic about a December interest rate cut. Futures tied to the Dow Jones Industrial Average added 51 points, or 0.1%. S&P … [+3077 chars]',
     'CNBC',
     'BUSINESS',
     'https://image.cnbcfm.com/api/v1/image/108235960-1764775161344-gettyimages-2249102880-AFP_86YG4PG.jpeg?v=1764775238&w=1920&h=1080',
     'https://www.cnbc.com/2025/12/03/stock-market-today-live-updates.html',
     '2025-12-04 11:28:00',
     NOW()),

    ('Alphabet''s AI Chips Are a Potential $900 Billion ''Secret Sauce'' - Bloomberg.com',
     'Alphabet Inc. investors are growing increasingly confident that the company''s semiconductors could represent a significant driver of future revenue for Google''s parent.',
     'Alphabet Inc. investors are growing increasingly confident that the companys semiconductors could represent a significant driver of future revenue for Googles parent. The success of Alphabets tensor… [+451 chars]',
     'Bloomberg',
     'TECHNOLOGY',
     'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iWbvHEkfvHJw/v1/1200x800.jpg',
     'https://www.bloomberg.com/news/articles/2025-12-04/alphabet-s-ai-chips-are-a-potential-900-billion-secret-sauce',
     '2025-12-04 10:48:18',
     NOW()),

    ('CRM Stock: Salesforce Rises. What Wall Street Is Excited About in Earnings. - Barron''s',
     'Salesforce stock rises as Wall Street analysts express excitement about the company''s latest earnings report and future prospects.',
     'NULL',
     'Barron''s',
     'BUSINESS',
     NULL,
     'https://www.barrons.com/articles/salesforce-earnings-stock-price-0d26fe5d',
     '2025-12-04 10:33:00',
     NOW()),

    ('4 reasons the economy''s worst-case scenario could be looming in 2026 - Business Insider',
     'Stagflation looks increasingly likely in 2026 as the economy looks on track to grow below-trend while inflation runs "uncomfortably" hot, RBC said.',
     'The worst-case scenario for the US economy could be a looming reality in 2026. RBC flagged the likelihood of stagflation in 2026 as the economy looks poised to post below-trend growth while inflati… [+4203 chars]',
     'Business Insider',
     'BUSINESS',
     'https://i.insider.com/6930720904d0f0a114f153f0?width=1200&format=jpeg',
     'https://www.businessinsider.com/stagflation-us-economy-recession-2026-inflation-outlook-slow-economic-growth-2025-12',
     '2025-12-04 10:30:00',
     NOW()),

    ('In an era of rising prices, computers have gotten cheaper. (And why that may end) - NPR',
     'One thing has bucked the trend of rising prices: computing. Technological advances have underpinned a consistent drop in the cost of computers. But experts say that this may be reaching a limit.',
     'NPR''s series Cost of Living: The Price We Pay is examining what''s driving price increases and how people are coping after years of stubborn inflation. How are higher prices changing the way you live?… [+5268 chars]',
     'NPR',
     'TECHNOLOGY',
     'https://npr.brightspotcdn.com/dims3/default/strip/false/crop/5333x3000+0+0/resize/1400/quality/100/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2F30%2F78%2Fcc44b994481aa1b4ddba17533958%2Fcost-of-living-lower-tech.jpg',
     'https://www.npr.org/2025/12/04/nx-s1-5609211/cost-of-living-cheaper-computers',
     '2025-12-04 10:00:00',
     NOW()),

    ('Goldman''s chief strategist is retiring after 31 years. Where he sees a bubble right now. - MarketWatch',
     'Kostin sees opportunities with consumer and healthcare stocks, as well as those that make more revenue from AI',
     'Steven Goldstein is based in London and responsible for MarketWatch''s coverage of financial markets in Europe, with a particular focus on global macro and commodities. Previously, he was Washington b… [+121 chars]',
     'MarketWatch',
     'BUSINESS',
     'https://images.mktw.net/im-765300/social',
     'https://www.marketwatch.com/story/goldmans-chief-strategist-is-retiring-after-31-years-where-he-sees-a-bubble-right-now-1ae69aa1',
     '2025-12-04 10:00:00',
     NOW()),

    ('U.S. health care is broken. Here are 3 ways it''s getting worse - NPR',
     'One year after UnitedHealthcare''s CEO was shot and killed, the crisis in U.S. health care is intensifying — even for the companies and investors who make money from it.',
     'One year after UnitedHealthcare''s CEO was shot and killed, the crisis in U.S. health care has gotten even worse in ways both obvious and hidden. People increasingly can''t afford health insurance. Th… [+8115 chars]',
     'NPR',
     'HEALTH',
     'https://npr.brightspotcdn.com/dims3/default/strip/false/crop/5500x3094+0+288/resize/1400/quality/100/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Fa2%2F95%2F2302695f4c7c833d96eee334d57d%2Fgettyimages-2187619590.jpg',
     'https://www.npr.org/2025/12/04/nx-s1-5629211/health-care-broken-costs-united-health-investors',
     '2025-12-04 10:00:00',
     NOW()),

    ('Bank of Japan faces a policy dilemma as government bond yields keep hitting new highs - CNBC',
     'Experts said the rise in yields is due to inflation running above target, hawkish remarks from the Bank of Japan and an expansionary fiscal policy.',
     'Japan''s central bank is caught in a bind as soaring government bond yields risk upending its policy normalization process. The Bank of Japan faces a stark choice: sticking with its policy of raising… [+4168 chars]',
     'CNBC',
     'BUSINESS',
     'https://image.cnbcfm.com/api/v1/image/107282501-1691382970595-gettyimages-1558501240-AFP_33Q72U4.jpeg?v=1696229932&w=1920&h=1080',
     'https://www.cnbc.com/2025/12/04/japan-record-high-jgb-yields-boj-policy-rate.html',
     '2025-12-04 04:01:00',
     NOW()),

    ('Huge recall of shredded cheese sold at Aldi, Target, Walmart amid metal fragment concerns - Axios',
     'Over 260,000 cases of shredded cheese sold at major retailers including Aldi, Target and Walmart are being recalled because the products may contain metal fragments.',
     'Over 260,000 cases of shredded cheese sold at major retailers including Aldi, Target and Walmart are being recalled because the products may contain metal fragments, according to a Food and Drug Admi… [+3430 chars]',
     'Axios',
     'GENERAL',
     'https://images.axios.com/C9g9XJ7XaC8nqe6d5VzjskUOen4=/0x0:4200x2363/1366x768/2025/12/04/1764811593114.jpeg',
     'https://www.axios.com/2025/12/04/shredded-cheese-recall-aldi-target-walmart-fda-list',
     '2025-12-04 02:41:45',
     NOW()),

    ('Who is Kevin Hassett, Trump''s expected pick to lead the Federal Reserve? - Al Jazeera',
     'Trump''s top economic adviser is odds-on favourite to lead the Fed amid concerns over the central bank''s independence.',
     'United States President Donald Trump has said he has decided on his pick for the next chair of the Federal Reserve. While Trump has yet to confirm his nominee, one name stands out as the overwhelmin… [+6285 chars]',
     'Al Jazeera English',
     'BUSINESS',
     'https://www.aljazeera.com/wp-content/uploads/2025/12/AP25317530239289-1764739234_038fa7-1764754672.jpg?resize=1200%2C630&quality=80',
     'https://www.aljazeera.com/economy/2025/12/4/who-is-kevin-hassett-trumps-expected-pick-to-lead-the-federal-reserve',
     '2025-12-04 02:15:57',
     NOW()),

    ('China Gives Most Forceful Signal Since 2022 to Slow Yuan Gains - Bloomberg.com',
     'China set its daily reference rate for the yuan at a level that was significantly weaker than estimated by traders and analysts, suggesting the central bank is aiming to cool gains in the managed currency.',
     'China set its daily reference rate for the yuan at a level that was significantly weaker than estimated by traders and analysts, suggesting the central bank is aiming to cool gains in the managed cur… [+294 chars]',
     'Bloomberg',
     'BUSINESS',
     'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/idWevaHW.qmY/v1/1200x800.jpg',
     'https://www.bloomberg.com/news/articles/2025-12-04/china-gives-most-forceful-signal-since-2022-to-slow-yuan-gains-miqr9x7o',
     '2025-12-04 01:27:00',
     NOW()),

    ('Donald Trump Pardons Entertainment Executive Tim Leiweke Just 5 Months After POTUS'' DOJ Charged Him In Bid-Rigging Scheme - Deadline',
     'Donald Trump granted Tim Leiweke a pardon, just five months after the administration''s Justice Department charged the live entertainment executive.',
     'Donald Trump granted Tim Leiweke a pardon, just five months after the administration''s Justice Department charged the live entertainment executive in a scheme to rig the bidding process for a public … [+2428 chars]',
     'Deadline',
     'ENTERTAINMENT',
     'https://deadline.com/wp-content/uploads/2025/07/Tim-Leiweke.jpg?w=1024',
     'http://deadline.com/2025/12/trump-pardons-tim-leiweke-1236635432/',
     '2025-12-04 01:20:00',
     NOW()),

    ('Tracy Beth Høeg, Makary aide who investigated Covid vaccines, to lead FDA drug center - statnews.com',
     'Tracy Beth Høeg, a top lieutenant to Food and Drug Administration Commissioner Marty Makary, will be the next leader of the Center for Drug Evaluation and Research.',
     'WASHINGTON Tracy Beth Høeg, a top lieutenant to Food and Drug Administration Commissioner Marty Makary, will be the next leader of the Center for Drug Evaluation and Research, according to an announc… [+730 chars]',
     'STAT',
     'HEALTH',
     'https://www.statnews.com/wp-content/uploads/2025/11/AP25176703125800-1024x576.jpg',
     'https://www.statnews.com/2025/12/03/tracy-beth-hoeg-lead-center-for-drug-evaluation-and-research/',
     '2025-12-04 00:37:17',
     NOW()),

    ('12 former FDA chiefs unite to say agency memo on vaccines is deeply stupid - Ars Technica',
     'Prasad''s arguments "misrepresent both the science and the regulatory record" according to former FDA officials.',
     'NULL',
     'Ars Technica',
     'HEALTH',
     'https://cdn.arstechnica.net/wp-content/uploads/2022/07/GettyImages-1403288381-1152x648.jpeg',
     'https://arstechnica.com/health/2025/12/12-former-fda-chiefs-unite-to-say-agency-memo-on-vaccines-is-deeply-stupid/',
     '2025-12-04 00:06:58',
     NOW()),

    ('Trump proposal would weaken vehicle mileage rules that limit air pollution - AP News',
     'President Donald Trump has announced a proposal to weaken vehicle mileage rules for the auto industry. If the plan announced Wednesday is finalized next year, it would ease pressure on automakers to control pollution from gasoline-powered cars and trucks.',
     'WASHINGTON (AP) President Donald Trump on Wednesday announced a proposal to weaken vehicle mileage rules for the auto industry, loosening regulatory pressure on automakers to control pollution from g… [+6980 chars]',
     'Associated Press',
     'GENERAL',
     'https://dims.apnews.com/dims4/default/2c0f2e4/2147483647/strip/true/crop/5236x2945+0+273/resize/1440x810!/quality/90/?url=https%3A%2F%2Fassets.apnews.com%2F27%2F4c%2F5682ffe7ce2074b5046a218c9e93%2Feef84401801e4c7c90c25b2e7efc1029',
     'https://apnews.com/article/trump-gas-mileage-per-gallon-electric-vehicles-363fcad4bb90a0859f6906d086aeac69',
     '2025-12-04 00:01:00',
     NOW()),

    ('Paramount Raises Breakup Fee in Warner Bros. Bid to $5 Billion - Bloomberg.com',
     'Paramount Skydance Corp. more than doubled the proposed breakup fee in its offer to acquire Warner Bros. Discovery Inc. to $5 billion, according to people familiar with the company''s offer.',
     'Paramount Skydance Corp. more than doubled the proposed breakup fee in its offer to acquire Warner Bros. Discovery Inc. to $5 billion, according to people familiar with the companys offer, part of a … [+374 chars]',
     'Bloomberg',
     'ENTERTAINMENT',
     'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iX8IxSfPx.fc/v1/1200x800.jpg',
     'https://www.bloomberg.com/news/articles/2025-12-03/paramount-raises-breakup-fee-in-warner-bros-bid-to-5-billion',
     '2025-12-03 23:53:02',
     NOW()),

    ('All the biggest news from AWS'' big tech show re:Invent 2025 - TechCrunch',
     'Amazon Web Services'' giant tech conference re:Invent 2025 is happening this week with news ranging from chips to AI services.',
     'Amazon Web Services'' annual tech conference AWS re:Invent has wrapped up another day with a deluge of product news and keynotes plus the obligatory customer success stories. The unsurprising theme i… [+6637 chars]',
     'TechCrunch',
     'TECHNOLOGY',
     'https://techcrunch.com/wp-content/uploads/2024/11/GettyImages-2179195367.jpg?resize=1200,746',
     'https://techcrunch.com/2025/12/03/all-the-biggest-news-from-aws-big-tech-show-reinvent-2025/',
     '2025-12-03 23:43:25',
     NOW()),

    ('Nvidia''s Huang Unsure Whether China Would Accept Its H200 Chips - Bloomberg.com',
     'Nvidia Corp. Chief Executive Officer Jensen Huang said he''s unsure whether China would accept the company''s H200 artificial intelligence chips should the US relax restrictions on sales of the processors.',
     'Nvidia Corp. Chief Executive Officer Jensen Huang said hes unsure whether China would accept the companys H200 artificial intelligence chips should the US relax restrictions on sales of the processor… [+445 chars]',
     'Bloomberg',
     'TECHNOLOGY',
     'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iECrVF14ciak/v1/1200x800.jpg',
     'https://www.bloomberg.com/news/articles/2025-12-03/nvidia-s-huang-unsure-whether-china-would-accept-its-h200-chips',
     '2025-12-03 23:26:23',
     NOW()),

    ('''Exploitation is imminent'' as 39 percent of cloud environs have max-severity React hole - theregister.com',
     'A maximum-severity flaw in the widely used JavaScript library React, and several React-based frameworks including Next.js allows unauthenticated, remote attackers to execute malicious code on vulnerable systems.',
     'A maximum-severity flaw in the widely used JavaScript library React, and several React-based frameworks including Next.js allows unauthenticated, remote attackers to execute malicious code on vulnera… [+3934 chars]',
     'The Register',
     'TECHNOLOGY',
     'https://regmedia.co.uk/2025/12/03/shutterstock_2245564489.jpg',
     'https://www.theregister.com/2025/12/03/exploitation_is_imminent_react_vulnerability/',
     '2025-12-03 21:55:00',
     NOW()),

    ('Self-driving car company Waymo officially expands to Philadelphia, has started letting cars drive themselves - WHYY',
     'The company will expand to more than 20 cities, including Pittsburgh and Baltimore, but no word yet on when people will get to ride.',
     'The Navy Yard shuttle ended earlier this year. Perrone said his team found that there were some intersections with older traffic lights that even human drivers had trouble seeing, so they required hu… [+3316 chars]',
     'WHYY',
     'TECHNOLOGY',
     'https://whyy.org/wp-content/uploads/2025/12/waymo-philadelphia-2025.jpg',
     'http://whyy.org/articles/waymo-philadelphia-autonomous-cars/',
     '2025-12-03 19:52:34',
     NOW());